---
title: "Method Study"
output:
  rmarkdown::html_vignette:
    toc: true
    toc_depth : 3
    number_sections: true
    includes:
    css: vignette-style.css
vignette: >
  %\VignetteIndexEntry{MixedML with Reservoir Computing models from resersvoirpy}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits = 3)
devtools::load_all()
```


# Fitting HLME on residuals or using offset?


We consider our ML model perfectly predicts the fixed effects.

(We conveniently saved the fixed effects when generating our dataset,
but of course we do not have them in a real case scenario.)

## Fitting on residuals

We create a column with the residuals:
```{r}
data_mixedml$resid <- data_mixedml$ym - data_mixedml$yf
```


```{r}
model_resid <- hlme(
  fixed = resid ~ 1,
  random = ~ 1 + x1 + x2 + x3,
  subject = "ID",
  var.time = "time",
  data = data_mixedml,
  posfix = c(1),
  maxiter = 0,
  idiag = TRUE
)

model_resid$best[["intercept"]] <- 0.

model_resid <- update(model_resid, maxiter = 100, B = model_resid$best)
.check_convergence_hlme(model_resid)
summary(model_resid)
```


## Fitting with offset

```{r}
model_offset <- hlme(
  fixed = ym ~ 1 + yf, # offset is automatically added so let's make it explicit
  random = ~ 1 + x1 + x2 + x3,
  subject = "ID",
  var.time = "time",
  data = data_mixedml,
  posfix = c(1, 2),
  maxiter = 0,
  idiag = TRUE
)

model_offset$best[["intercept"]] <- 0.
model_offset$best[["yf"]] <- 1.

model_offset <- update(model_offset, maxiter = 100, B = model_offset$best)
.check_convergence_hlme(model_offset)
summary(model_offset)
```

## Comparaison

```{r}
print(model_resid$best[-1])
print(model_offset$best[c(-1, -2)])
stopifnot(model_resid$best[-1] == model_offset$best[c(-1, -2)])
```

```{r}
print(model_resid$loglik)
print(model_offset$loglik)
stopifnot(model_resid$loglik == model_offset$loglik)
```

Both methods are equivalent
