# you can use `act` to check this Github actions locally
# comment/uncomment the `ACT_SKIP_FILTERS: true` if you want to skip/use the action filters based on filenames
# (comment it before pushing to github as filtering makes the CI pipeline much faster)

on:
  push:
    branches: main
  pull_request:
    branches: main

name: QA-pipeline.yaml

permissions: read-all

jobs:
  QA-pipeline:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      # ACT_SKIP_FILTERS: true

    steps:

      - uses: actions/checkout@v4

      # actions filters on filenames
      - uses: dorny/paths-filter@v3
        id: changesdevt
        with:
          base: main
          filters: |
            python:
              - '**/*.py'
            R:
              - '**/*.R'
              - '**/*.rda'
              - '**/*.Rmd'
              - '**/*.py'

      #
      - name: README.md rendered 1
        shell: bash
        run: test README.md -nt README.Rmd

      - name: README.md rendered 2
        shell: bash
        run: test README.md -nt vignettes/mixedML.Rmd

      - name: README.md rendered 3
        shell: bash
        run: test README.md -nt vignettes/work_with_Python.Rmd

      # R installs
      - uses: r-lib/actions/setup-r@v2
        if: steps.changes.outputs.R == 'true' || env.ACT_SKIP_FILTERS == 'true'
        with:
          r-version: '3.5.3'

      - uses: r-lib/actions/setup-r-dependencies@v2
        if: steps.changes.outputs.R == 'true' || env.ACT_SKIP_FILTERS == 'true'
        with:
          extra-packages: |
            any::rcmdcheck
            any::lintr
          needs: check
          cache: true
          cache-version: 1

      # R Basic/fast checks

      - name: Lint root directory
        if: steps.changes.outputs.R == 'true' || env.ACT_SKIP_FILTERS == 'true'
        run: lintr::lint_dir()
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true


      # Python installs

      - uses: actions/setup-python@v6
        if: steps.changes.outputs.python == 'true' || env.ACT_SKIP_FILTERS == 'true'
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Python dependencies
        if: steps.changes.outputs.python == 'true' || env.ACT_SKIP_FILTERS == 'true'
        uses: py-actions/py-dependency-install@v4
        with:
          path: 'inst/python/requirements-dev.txt'

      # Python Basic/fast checks

      - name: mypy
        if: steps.changes.outputs.python == 'true' || env.ACT_SKIP_FILTERS == 'true'
        shell: bash
        run: mypy inst/python

      - name: Python Black
        if: steps.changes.outputs.python == 'true' || env.ACT_SKIP_FILTERS == 'true'
        shell: bash
        run: black inst/python

      - name: flake8 Lint
        if: steps.changes.outputs.python == 'true' || env.ACT_SKIP_FILTERS == 'true'
        shell: bash
        run: flake8 inst/python


      # Python tests (first because a Python error will be less obvious with R CMD check)

      - name: Run pytest
        if: steps.changes.outputs.python == 'true' || env.ACT_SKIP_FILTERS == 'true'
        shell: bash
        run: pytest

      # R full checks

      - name: Configure Reticulate Environement Variable
        shell: bash
        run: echo RETICULATE_PYTHON=$(which python)  >> $GITHUB_ENV

      - uses: r-lib/actions/check-r-package@v2
        if: steps.changes.outputs.R == 'true' || env.ACT_SKIP_FILTERS == 'true'
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'


      # warning
      - shell: bash
        if:  env.ACT_SKIP_FILTERS == 'true'
        run: echo "Actions filters on filenames were skipped. PLEASE reactivate them before pushing on Github!"
